apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: cruzexfacerecognitionbrain 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cruzexfacerecognitionbrain 
    spec:
      containers:
        - name: cruzexfacerecognitionbrain 
          image: thvargacr007.azurecr.io/cruzexfacerecognitionbrain
          ports:
          - containerPort: 3000